version: '3'
services:
  server:
    build:
      context: ./app/server
      dockerfile: Dockerfile
    container_name: server
    command: ["50051"]
    tty: true
    stdin_open: true
    volumes:
      - './app/server:/app'
    ports:
      - "50051:50051"
    networks:
      - cache_network

  search:
    build:
      context: ./app/search
      dockerfile: Dockerfile
    container_name: search
    #command: ["search", "50051"]  # Puedes configurar el comando si es necesario
    tty: true
    stdin_open: true
    volumes:
      - './app/search:/app'
      - './data_gen/cars.json:/app/cars.json'
    networks:
      - cache_network
    restart: always
    depends_on: 
      - server

networks:
  cache_network:
